export const LOGIN = 'LOGIN';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGOUT = 'LOGOUT';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const REQUEST_VERIFY_TOKEN = 'REQUEST_VERIFY_TOKEN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const ERROR_VERIFY_TOKEN = 'ERROR_VERIFY_TOKEN';
